baseurl = "https://joycetagal.me"
title = "Joyce Tagal"
author = "Joyce Tagal"
canonifyurls = false
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false
toc = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Joyce Tagal"
  customCss = ["css/custom.css"]

[[menu.main]]
    name = "Home"
    url = "https://joycetagal.me/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/joycektagal"
    weight = 4
    pre = "<i class='fa fa-twitter'></i> "
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jayktee"
    weight = 5
    pre = "<i class='fa fa-github'></i> "
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/joycetagal"
    weight = 6
    pre = "<i class='fa fa-linkedin'></i> "


